version: '3'

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:80"
    environment:
      APP_HOST: ":80"
    depends_on:
      - frontend
      - api
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:z
      - caddy-data:/data

  frontend:
    build:
        context: ./front-ui
        dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - SSR_BASE_URL=http://api:3000/
      - BROWSER_BASE_URL=http://${APP_HOST:-localhost}:${APP_PORT:-3000}/api/v1
    volumes:
      - ./front-ui:/app:z

  api:
    build: ./central-api
    restart: unless-stopped
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - DB_URL=/data/riptide.db
      - BASE_URL=http://${APP_HOST:-localhost}:${APP_PORT:-3000}/api/v1
      - REQUEST_TIMEOUT
      - AUTH_TIMEOUT
      - PING_INTERVAL
      - SERVER_PASS
    volumes:
      - sqlite-db-data:/data

volumes:
  sqlite-db-data:
  caddy-data:
